# Generic ARM64 Device Configuration

PRODUCT_NAME := aetheros_arm64
PRODUCT_DEVICE := generic_arm64
PRODUCT_BRAND := AetherOS
PRODUCT_MODEL := Generic ARM64 Device
PRODUCT_MANUFACTURER := AetherOS

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

# Kernel
TARGET_KERNEL_SOURCE := $(AETHEROS_ROOT)/src/kernel
TARGET_KERNEL_CONFIG := aetheros_arm64_defconfig

# Display
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400
TARGET_SCREEN_DENSITY := 420

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_USERDATAIMAGE_PARTITION_SIZE := 10737418240
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456

# Filesystem
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Features
BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true
BOARD_USES_WAYLAND := true
BOARD_USES_PIPEWIRE := true
